version: "3.9"
services:
  test-db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
    ports:
      - "5432:5432"
    command: postgres -N 1000